export const GET_ORDERS_COMPLETED_REQUEST = 'GET_ORDERS_COMPLETED_REQUEST'
export const GET_ORDERS_COMPLETED_SUCCESS = 'GET_ORDERS_COMPLETED_SUCCESS'
export const GET_COMPLETED_ORDER_REQUEST = 'GET_ORDER_COMPLETE_REQUEST'
export const GET_COMPLETED_ORDER_SUCCESS = 'GET_ORDER_COMPLETE_SUCCESS'