export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST'
export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST'
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS'
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS'
